Replaced abort() by Flask Exceptions, closes #3
OpenCycleCompass/ocyco-server-python pull request #12
Opened 2017-01-21 22:21 UTC by AlissaWe

- new exception classes
- new error handlers
- replaced every use of `abort()` with `raise exception()`

2017-01-22 03:42 UTC, rleh requested changes

2017-01-22 03:42 UTC, rleh commented on ocyco/api/decorators.py
> +from ocyco.api.exceptions import OcycoException, ParameterInvalidException, ParameterMissingException, NotFoundException, ConflictExistingObjectException, MultipleMatchesException, PhotonException
You don't need to import all exception, only `MultipleMatchesException` is needed here.

2017-01-22 03:42 UTC, rleh commented on ocyco/api/exceptions.py
> +        Exception.__init__(self)
Does this work? I think you should call `OcycoException.__init__(self)` here...

2017-01-22 03:42 UTC, rleh commented on ocyco/api/exceptions.py
> +        Exception.__init__(self)
see above

2017-01-22 03:42 UTC, rleh commented on ocyco/api/geo.py
> +from ocyco.api.exceptions import OcycoException, ParameterInvalidException, ParameterMissingException, NotFoundException, ConflictExistingObjectException, MultipleMatchesException, PhotonException
Only `ParameterMissingException` is needed, see above.

2017-01-22 03:42 UTC, rleh commented on ocyco/api/tracks.py
> +from ocyco.api.exceptions import OcycoException, ParameterInvalidException, ParameterMissingException, NotFoundException, ConflictExistingObjectException, MultipleMatchesException, PhotonException
see above

2017-01-23 18:06 UTC, rleh approved these changes

2017-01-23 21:43 UTC, Harry-R commented
Thanks for your contribution! 👍

2017-01-23 21:43 UTC, merged